### ISSUE TITLE
getting this type of error

### ISSUE THREAD

**Issue by LATESTTIME** [sillibird/hqwords-client#1]
Traceback (most recent call last):
  File "main.py", line 151, in <module>
    menuSwitch()
  File "main.py", line 80, in menuSwitch
    asyncio.get_event_loop().run_until_complete(playGame())
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line466, in run_until_complete
    return future.result()
  File "main.py", line 88, in playGame
    client = pyhq.HQClient(loginToken)
  File "/home/runner/pyhq.py", line 75, in __init__
    self.auth_token = self.get_auth_token()
  File "/home/runner/pyhq.py", line 86, in get_auth_token
    return requests.post("https://api-quiz.hype.space/tokens/", headers=self.headers, data={'token': self.login_token}).json()['authToken']
KeyError: 'authToken'

**Comment by bird** [comment]
Make sure when inputting the token, you use a login token instead of an auth token.
